# LEGACY-COMPAT build of the semantic-release image for the CENTRAL
# registry only (build context: repo root, see .gitlab-ci-yaml-custom.yaml).
#
# The shipped definition (semantic-release/Dockerfile) is self-contained:
# repos generated by current catladder run the security audit via the
# materialized `.catladder-generated/catci/` bundle. But the central
# `:latest` tag is shared with repos on OLD catladder versions whose
# generated pipelines expect `catladder` on the PATH — so the central
# build additionally bakes the cli in, exactly as before.
#
# Delete together with the central registry / central mode.
FROM node:lts-alpine

RUN apk add --no-cache bash git git-lfs

RUN mkdir /packages
COPY ./cli /packages/cli

# add semantic release
RUN yarn global add \
    semantic-release@^19 \
    @semantic-release/commit-analyzer \
    @semantic-release/release-notes-generator \
    https://github.com/panter/git.git#b4037626cc583d3e9f7995ea0604b23730d0a22e \
    @semantic-release/changelog \
    @semantic-release/gitlab@9 \
    @semantic-release/exec@6 \
    /packages/cli

RUN mkdir -p /scripts
COPY ./runner-images/semantic-release/scripts/* /scripts/
RUN chmod +x /scripts/*

ENV PATH="/scripts:${PATH}"
