#!/bin/bash

# ensure nginx config
echo "ensureNginxDockerfile in $APP_DIR"

if [ ! -f $APP_DIR/nginx.conf ]; then
    echo "Creating nginx.conf"

    cat >$APP_DIR/nginx.conf <<NGINX
    
server {
    listen       8080;
    server_name  localhost;
    error_page 404 =200 /index.html;

    charset utf-8;

    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "SAMEORIGIN";

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /__health {
        access_log off;
        types { } default_type "text/html; charset=utf-8";
        return 200 "ok\n";
    }
}


NGINX

fi
# ensure docker ignore
if [ ! -f $APP_DIR/.dockerignore ]; then

    cat >.dockerignore <<EOF
**/node_modules
**/__snapshots__/**
.git

EOF

fi

if [ ! -f $APP_DIR/Dockerfile ]; then
    echo "Creating Dockerfile"

    cat >$APP_DIR/Dockerfile <<EOF

$DOCKERFILE_ADDITIONS

FROM nginx:stable
WORKDIR /app

RUN sed --in-place "s/^\s*user .*//" /etc/nginx/nginx.conf && \
    chown -R nginx:nginx /app && \
    chmod -R 755 /app && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chown -R nginx:nginx /etc/nginx/conf.d && \
    touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid

COPY $APP_DIR/nginx.conf /etc/nginx/conf.d/default.conf
COPY $APP_DIR/dist/ /usr/share/nginx/html/

$DOCKERFILE_ADDITIONS_END

USER nginx
EXPOSE 8080

EOF
fi
