#!/bin/bash

if [ ! -f $APP_DIR/.dockerignore ]; then

    cat >$APP_DIR/.dockerignore <<EOF
$APP_DIR/node_modules
**/__snapshots__/**
.git

EOF
fi

if [ ! -f $APP_DIR/Dockerfile ]; then
    echo "Creating Dockerfile"
    if [[ ! -z "$METEOR_OVERRIDE_NODE_VERSION" ]]; then
        NODE_VERSION=$METEOR_OVERRIDE_NODE_VERSION
    else
        NODE_VERSION_FULL=$(cat $APP_DIR/dist/bundle/.node_version.txt)
        NODE_VERSION=${NODE_VERSION_FULL/v/} # remove v
    fi
    if [ "$NODE_VERSION" = "14.21.4" ]; then
        DOCKER_IMAGE="meteor/node:$NODE_VERSION" # meteor maintenance for because of fibers
    else
        DOCKER_IMAGE="node:$NODE_VERSION"
    fi
    INSTALL_SCRIPTS=""
    if [[ $METEOR_INSTALL_SCRIPTS == "true" ]]; then
        read -d '' INSTALL_SCRIPTS <<EOF

COPY $APP_DIR/package.json $APP_DIR/yarn.lock ./

RUN yarn --frozen-lockfile --production=true --ignore-scripts --ignore-engines
COPY $APP_DIR .
RUN yarn --frozen-lockfile --production=true --ignore-engines
EOF
    fi

    cat >$APP_DIR/Dockerfile <<EOF
FROM $DOCKER_IMAGE

# install yarn. new meteor image has no yarn installed
npm install --global yarn


$DOCKERFILE_ADDITIONS

# we copy also source code and scripts for commands
# This is technically not required for meteor, but useful if we have additional scripts 
WORKDIR /src
$INSTALL_SCRIPTS


# copy the bundle
COPY $APP_DIR/dist /src/dist

# now install meteor deps
RUN cd /src/dist/bundle/programs/server && npm install

$DOCKERFILE_ADDITIONS_END

WORKDIR /src/dist/bundle

CMD ["node", "main.js"]
EOF

fi
