apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-app-secrets
  labels:
    app: {{ .Release.Name }}
data:
  {{- range $key, $val := .Values.env.secret }}
  {{if not (eq $key "cloudsqlProxyCredentials")}}
    {{ $key }}: {{ $val | b64enc }}
  {{- end}}
  {{- end}}
