{{- if .Values.application.enabled -}}
{{- $context := . }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "fullname" . }}-app
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ template "fullname" . }}-service
    {{- range $ports := .Values.service.additionalPorts }}
    - port: {{ required ".Values.service.additionalPorts.port is required" $ports.port }}
      targetPort: {{ $ports.targetPort | default $ports.port }}
      protocol: {{ $ports.protocol | default "TCP" }}
      name: {{ template "fullname" $context }}-{{ required ".Values.service.additionalPorts.nameSuffix is required" $ports.nameSuffix }}-service
    {{- end }}
  selector:
    app: {{ template "fullname" . }}-app
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: NodePort
{{- end -}}