
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-app-env
  labels:
    app: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  PORT: "8080"
  TZ: Europe/Zurich
  ENV_SHORT: {{ .Values.global.ENV_SHORT }}
  SERVICE_VAR_PREFIX: "{{- template "serviceVarPrefix" . -}}"
  {{ if .Values.mongodb.enabled }}
  MONGO_URL: "{{- template "MONGO_URL" . -}}"
  {{- end -}}

  {{ if .Values.prisma.enabled }}
  PRISMA_ENDPOINT: "{{- template "PRISMA_ENDPOINT" . -}}"
  {{- end -}}

  {{ if .Values.mailhog.enabled }}
  MAILHOG_SMTP_URL: "{{- template "MAILHOG_SMTP_URL" . -}}"
  MAIL_URL: "{{- template "MAILHOG_SMTP_URL" . -}}"
  {{- end -}}

  {{- range $key, $val := .Values.env.public }}
  {{ $key }}: {{ template "envValue" $val }}
  {{- end -}}
  
 

  

