{{- if .Values.cloudsql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-cloudsql-proxy-credentials
  labels:
    app: {{ .Release.Name }}
data:
  credentials.json: {{ .Values.cloudsql.proxyCredentials | b64enc}}
{{- end }}