
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-scripts
  labels:
    app: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  additionalEnv: | 
    HOST_VAR="$SERVICE_VAR_PREFIX"_WORKER_SERVICE_HOST
    PORT_VAR="$SERVICE_VAR_PREFIX"_WORKER_SERVICE_PORT
    export WORKER_SERVICE_LOCAL_URL=$(eval echo "http://\$$HOST_VAR:\$$PORT_VAR")

    HOST_VAR="$SERVICE_VAR_PREFIX"_APP_SERVICE_HOST
    PORT_VAR="$SERVICE_VAR_PREFIX"_APP_SERVICE_PORT
    export APP_SERVICE_LOCAL_URL=$(eval echo "http://\$$HOST_VAR:\$$PORT_VAR")

