image: node:14
variables:
  INLINE_VERSION_TAG: $CI_COMMIT_SHA # this gets inlined into files

build-packages:
  cache:
    - key: node-modules
      policy: pull-push
      paths:
        - node_modules
        - "**/node_modules/"
  stage: "build"
  script:
    - yarn install
    - yarn workspaces run build
  artifacts:
    paths:
      - "*/dist"

.docker-build-base:
  image: docker:20
  interruptible: true
  services:
    - name: docker:20-dind
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: $CI_REGISTRY_IMAGE/$COMPONENT_NAME
    CACHE_IMAGE: $CI_REGISTRY_IMAGE/$COMPONENT_NAME/cache:cache

.docker-build-app-base:
  extends: .docker-build-base
  script:
    - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CACHE_IMAGE || true
    - docker build --network host --cache-from $CACHE_IMAGE --tag $IMAGE_NAME:$INLINE_VERSION_TAG $DOCKER_DIR
    - docker push $IMAGE_NAME:$INLINE_VERSION_TAG
    - docker tag $IMAGE_NAME:$INLINE_VERSION_TAG $CACHE_IMAGE
    - docker push $CACHE_IMAGE

build-runner-image-pipeline:
  needs: ["build-packages"]
  stage: build
  image: docker:20
  variables:
    COMPONENT_NAME: gitlab-pipeline
    DOCKER_DIR: "./images/dockerfiles/pipeline"
  extends:
    - .docker-build-app-base

docker-build-docker-in-docker:
  needs: ["build-packages"]
  stage: build
  image: docker:20
  variables:
    COMPONENT_NAME: gitlab-docker-build
    DOCKER_DIR: "./images/dockerfiles/docker-build"
  extends:
    - .docker-build-app-base
