# this project initially did not use catladder to create the gitlab pipeline
# but we started to use some of its feature also for its own pipeline.
# This file here is the the original hand written gitlab-ci yaml which gets imported by catladder

image: node:20
variables:
  INLINE_DOCKER_REGISTRY: $CI_REGISTRY_IMAGE
  DOCKER_HOST: tcp://docker:2376
  INLINE_PIPELINE_IMAGE_TAG: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" # we need to add the commit sha because the docker policy currently does not download images if already in cache with the same tag

  KUBERNETES_CPU_REQUEST: "0.45"
  KUBERNETES_MEMORY_REQUEST: "1Gi"
  KUBERNETES_MEMORY_LIMIT: "4Gi"
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn/cache

.base-rules:
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        SHOULD_MINIFY: "1"
    - if: $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/ # not after semantic release commits
      when: never
    - if: $CI_COMMIT_BRANCH =~ /^[0-9]+\.([0-9]+|x)\.x$/ # hotfix branches
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
    - when: never

.yarn-cache:
  cache:
    - key: yarn
      policy: pull-push
      paths:
        - .yarn/cache
        - node_modules
        - "**/node_modules/"

test:
  stage: "test"
  interruptible: true
  variables:
    KUBERNETES_MEMORY_LIMIT: "8Gi"
    KUBERNETES_MEMORY_REQUEST: "6Gi"
  extends:
    - .base-rules
    - .yarn-cache
  script:
    - yarn install --immutable
    - yarn test

🔨 packages:
  stage: "build"
  interruptible: true
  needs: [] # don't wait for test atm
  extends:
    - .base-rules
    - .yarn-cache
  script:
    - yarn install --immutable
    - yarn build
  artifacts:
    paths:
      - "*/dist"

.docker-build-base:
  image: docker:24
  needs: []
  interruptible: true
  retry: 2 # ugly hack for https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27384
  services:
    - name: docker:24.0.6-dind # https://github.com/docker-library/docker/issues/463
      command: ["--registry-mirror=https://mirror.gcr.io"]
  extends:
    - .base-rules
  stage: build
  variables:
    DOCKER_BUILDKIT: "1"
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    IMAGE_NAME: $CI_REGISTRY_IMAGE/$NAME
    CACHE_IMAGE: $CI_REGISTRY_IMAGE/$NAME/cache:cache
    BUILD_CONTEXT: ./runner-images/$NAME
    DOCKER_FILE: ./runner-images/$NAME/Dockerfile
  script:
    - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --network host --cache-from $CACHE_IMAGE --tag $IMAGE_NAME:$INLINE_PIPELINE_IMAGE_TAG -f $DOCKER_FILE $BUILD_CONTEXT --build-arg BUILDKIT_INLINE_CACHE=1
    - docker push $IMAGE_NAME:$INLINE_PIPELINE_IMAGE_TAG
    - docker tag $IMAGE_NAME:$INLINE_PIPELINE_IMAGE_TAG $CACHE_IMAGE
    - docker push $CACHE_IMAGE
    # when is a release (has tag), also push as latest
    - if [ -n "$CI_COMMIT_TAG" ]; then
      docker tag $IMAGE_NAME:$INLINE_PIPELINE_IMAGE_TAG $IMAGE_NAME:latest;
      docker push $IMAGE_NAME:latest;
      fi

🔨 runner kubernetes:
  variables:
    NAME: kubernetes
  extends:
    - .docker-build-base

.docker-build-jobs-base:
  variables:
    BUILD_CONTEXT: ./runner-images
  extends:
    - .docker-build-base

🔨 runner jobs-default:
  variables:
    NAME: jobs-default
  extends:
    - .docker-build-jobs-base

🔨 runner jobs-meteor:
  variables:
    NAME: jobs-meteor
  extends:
    - .docker-build-jobs-base

🔨 runner agent-claude:
  variables:
    NAME: agent-claude
  extends:
    - .docker-build-jobs-base

🔨 runner jobs-testing-chrome:
  variables:
    NAME: jobs-testing-chrome
  extends:
    - .docker-build-jobs-base

🔨 runner docker-in-docker:
  variables:
    NAME: docker-build
  extends:
    - .docker-build-base
🔨 runner semantic-release:
  needs: ["🔨 packages"]
  variables:
    NAME: semantic-release
    BUILD_CONTEXT: .
  extends:
    - .docker-build-base
🔨 runner gcloud:
  variables:
    NAME: gcloud
  extends:
    - .docker-build-base

.npm-publish-base:
  interruptible: true
  image: node:14 # npm publish has some problem with node 16
  extends:
    - .base-rules
    - .yarn-cache
  needs: ["🔨 packages"]
  stage: deploy
  retry: 1 # https://github.com/npm/feedback/discussions/796
  script:
    - VERSION=$([ "$CI_COMMIT_TAG" ] && echo "${CI_COMMIT_TAG#'v'}" || echo "0.0.0-$INLINE_PIPELINE_IMAGE_TAG")
    - echo "publish version $VERSION"
    - yarn workspaces foreach version $VERSION --deferred
    - yarn version apply -R --all
    - cd $DIR
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - |
      DIST_TAG=$( 
        if [ "$CI_COMMIT_TAG" ]; then 
          echo "latest" 
        elif [ "$CI_COMMIT_REF_SLUG" = "beta" ] || [ "$CI_COMMIT_REF_SLUG" = "next" ]; then 
          echo "$CI_COMMIT_REF_SLUG" 
        else 
          echo "canary" 
        fi 
      )
    - echo "publishing with tag $DIST_TAG"
    - npm publish --tag $DIST_TAG --no-git-tag-version --access public

🚀 cli:
  extends: .npm-publish-base
  variables:
    DIR: cli

🚀 pipeline:
  extends: .npm-publish-base
  variables:
    DIR: pipeline

pages:
  stage: deploy
  extends: [.yarn-cache, .base-rules]
  allow_failure: true
  interruptible: true
  script:
    - echo "Pages accessible through ${CI_PAGES_URL}/${PAGES_PREFIX}"
    - yarn install
    - yarn workspace docs gen-examples-md
    - yarn workspace docs build
  variables:
    PAGES_PREFIX: "" # No prefix by default (master)
  pages:
    path_prefix: "$PAGES_PREFIX"
  artifacts:
    paths: [public]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run on default branch (with default PAGES_PREFIX)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Conditionally change the prefix for Merge Requests
      when: manual # Run pages manually on Merge Requests
      variables:
        PAGES_PREFIX: "mr-$CI_MERGE_REQUEST_IID" # Prefix with the mr-<iid>, like `mr-123`
