image: node:14
variables:
  INLINE_DOCKER_REGISTRY: $CI_REGISTRY_IMAGE
  DOCKER_HOST: tcp://0.0.0.0:2375
  DOCKER_TLS_CERTDIR: ""
  INLINE_PIPELINE_IMAGE_TAG: "$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" # we need to add the commit sha because the docker policy currently does not download images if already in cache with the same tag

stages:
  - test
  - build
  - deploy
  - release

workflow:
  rules:
    [
      { if: "$CI_COMMIT_TAG" },
      { if: "$CI_COMMIT_MESSAGE =~ /^chore(release).*/", when: "never" },
      { if: "$CI_COMMIT_BRANCH =~ /^[0-9]+.([0-9]+|x).x$/" },
      { if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" },
      { if: "$CI_MERGE_REQUEST_ID" },
    ]

🔨 packages:
  cache:
    - key: node-modules
      policy: pull-push
      paths:
        - node_modules
        - "**/node_modules/"
  stage: "build"
  script:
    - yarn install
    - yarn workspaces run build
  artifacts:
    paths:
      - "*/dist"

.docker-build-base:
  image: docker:20
  interruptible: true
  services:
    - name: docker:20-dind
      command: ["--tls=false"]

  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: $CI_REGISTRY_IMAGE/$NAME
    CACHE_IMAGE: $CI_REGISTRY_IMAGE/$NAME/cache:cache
    BUILD_CONTEXT: ./runner-images/$NAME
    DOCKER_FILE: ./runner-images/$NAME/Dockerfile
  script:
    - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CACHE_IMAGE || true
    - docker build --network host --cache-from $CACHE_IMAGE --tag $IMAGE_NAME:$INLINE_PIPELINE_IMAGE_TAG -f $DOCKER_FILE $BUILD_CONTEXT
    - docker push $IMAGE_NAME:$INLINE_PIPELINE_IMAGE_TAG
    - docker tag $IMAGE_NAME:$INLINE_PIPELINE_IMAGE_TAG $CACHE_IMAGE
    - docker push $CACHE_IMAGE

🔨 runner base-pipeline:
  needs: ["🔨 packages"]
  variables:
    NAME: "base-pipeline"
    BUILD_CONTEXT: .
  extends:
    - .docker-build-base

🔨 runner kubernetes:
  variables:
    NAME: kubernetes
  extends:
    - .docker-build-base

🔨 runner jobs:
  variables:
    NAME: jobs
  extends:
    - .docker-build-base

🔨 runner docker-in-docker:
  variables:
    NAME: docker-build
  extends:
    - .docker-build-base
🔨 runner semantic-release:
  variables:
    NAME: semantic-release
  extends:
    - .docker-build-base

🚀 includes:
  needs: ["🔨 packages"]
  variables:
    VERSION_TAG: $CI_COMMIT_REF_SLUG
  stage: deploy
  script:
    - 'echo "version: $VERSION_TAG"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ci-includes/dist/includes/gitlab-ci.yml "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/ci-includes/$VERSION_TAG/gitlab-ci.yml"'

🚀 cli:
  needs: ["🔨 packages"]
  variables:
    VERSION_TAG: $CI_COMMIT_REF_SLUG
  stage: deploy
  script:
    - VERSION=$([ "$CI_COMMIT_TAG" ] && echo "$CI_COMMIT_TAG" || echo "0.0.0-$VERSION_TAG")
    - echo "publish version $VERSION"
    - cd cli
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">.npmrc
    - cat .npmrc
    - yarn publish --new-version $VERSION --tag canary --verbose

create release:
  stage: release
  image: $INLINE_DOCKER_REGISTRY/semantic-release:INLINE_PIPELINE_IMAGE_TAG
  script:
    - semanticRelease
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" # do not allow creating releases in a monorepo. this will handled in the parent pipeline insead
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /^chore\(release\).*/ # not after semantic release commit
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $AUTO_RELEASE == "true"
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - if: $CI_COMMIT_BRANCH =~ /^[0-9]+\.([0-9]+|x)\.x$/ # hotfix branches
      when: manual
