#!/bin/bash

export BUILD_TAG="$(git describe --tags || git rev-parse HEAD)"
export BUILD_ID="$BUILD_TAG"
export BUILD_COMMIT="$(git rev-parse HEAD)"
export BUILD_TIME="$(date)"
echo "BUILD_TAG=$BUILD_TAG" >>build.env
echo "BUILD_ID=$BUILD_ID" >>build.env
echo "BUILD_COMMIT=$BUILD_COMMIT" >>build.env
echo "BUILD_TIME=$BUILD_TIME" >>build.env
echo '{"id":"'$BUILD_ID'","commit":"'$BUILD_COMMIT'","tag":"'$BUILD_TAG'","time":"'$BUILD_TIME'"}' >__build_info.json
