import { writeFile } from "fs/promises";
import { stringify } from "yaml";
import type { Config } from "../types";
import type { BaseHookContext } from "../types/hooks";

type WriteFileOptions = {
  commentChar: string;
};

/**
 * the line that marks a file as catladder-generated. Cleanup code uses
 * it to tell a generated file apart from a hand-maintained one at the
 * same path (e.g. a `.gitlab-ci.yml` a project wrote itself).
 */
export const GENERATED_FILE_MARKER =
  "🐱 🔨 This file is generated by catladder";

type StringifyOptions = Exclude<
  Parameters<typeof stringify>[2],
  null | undefined | string | number
>;
export const yamlStringifyOptions: StringifyOptions = {
  // prevents colapsing long command statements into multiple lines
  lineWidth: 0,
  // represent multi line commands as single line json strings
  doubleQuotedAsJSON: true,
  // Better readability when bash commands most often use double quotes
  singleQuote: true,
};

export class FileWriter {
  public static create(config: Config) {
    return new FileWriter(config);
  }

  constructor(private readonly config: Config) {
    this.config = config;
  }

  protected async writeTheFile(path: string, content: string) {
    const transformedContent =
      await this.config.hooks?.transformFileBeforeWrite?.({
        ...(await this.getBaseHookContext(path)),
        content,
      });
    await writeFile(path, transformedContent ?? content, {
      encoding: "utf-8",
    });
  }

  protected async getBaseHookContext(path: string): Promise<BaseHookContext> {
    const filename = path.split("/").pop() ?? "";
    return {
      filename,
      path,
      extension: path.split(".").pop() ?? "",
    };
  }

  /**
   * writes content verbatim (no auto-generated header) — e.g. for
   * materialized dockerfiles, where a leading comment would break
   * parser directives like `# syntax = ...`
   */
  public async writeGeneratedFileRaw(path: string, content: string) {
    await this.writeTheFile(path, content);
  }

  public async writeGeneratedFile(
    path: string,
    content: string,
    options: WriteFileOptions,
  ) {
    await this.writeTheFile(
      path,
      [this.getAutoGeneratedHeader(options.commentChar), content].join("\n"),
    );
  }

  public async writeYamlfile(path: string, data: any) {
    const dataTransformed = await this.config.hooks?.transformYamlBeforeWrite?.(
      {
        ...(await this.getBaseHookContext(path)),
        data,
      },
    );
    return this.writeGeneratedFile(
      path,
      stringify(dataTransformed ?? data, yamlStringifyOptions),
      {
        commentChar: "#",
      },
    );
  }

  protected getAutoGeneratedHeader(commentChar: string) {
    return [
      "-------------------------------------------------",
      GENERATED_FILE_MARKER,
      `🚨 Do not edit this file manually 🚨`,
      "-------------------------------------------------",
    ]
      .map((line) => `${commentChar} ${line}`)
      .join("\n")
      .concat("\n");
  }
}
