import { readFile } from "fs/promises";
import { join } from "path";
import type { Config } from "@catladder/pipeline";
import {
  getEnabledPipelineTypes,
  GithubBackend,
  JobImagesPlan,
  resolveGithubRegistryImage,
} from "@catladder/pipeline";
import { parse } from "yaml";
import type { DoctorReport } from "./DoctorReport";

const WORKFLOWS_FOLDER = ".github/workflows";

/** the job name of the release job, see githubReleaseJobs.ts */
const RELEASE_JOB_NAME = "create release";

type Workflows = Awaited<ReturnType<GithubBackend["createWorkflows"]>>;

export type ReleaseJobImageDrift = {
  file: string;
  expected: string;
  /** null when the committed workflow has no release job (or no file) */
  committed: string | null;
};

const releaseJobImage = (workflow: {
  jobs?: Record<string, { name?: string; container?: unknown }>;
}): string | null => {
  const job = Object.values(workflow.jobs ?? {}).find(
    (job) => job?.name === RELEASE_JOB_NAME,
  );
  const container = job?.container;
  if (typeof container === "string") return container;
  if (container && typeof container === "object" && "image" in container) {
    return `${(container as { image: unknown }).image}`;
  }
  return null;
};

/**
 * compares the release job image of every generated workflow carrying
 * one against the committed workflow of the same name. The job images
 * are tagged by a content hash of their definition, so a differing tag
 * means the committed workflow runs an older release image.
 */
export const findReleaseJobImageDrift = (
  generated: Workflows,
  committed: Record<string, string | null>,
): ReleaseJobImageDrift[] =>
  Object.entries(generated).flatMap(([file, workflow]) => {
    const expected = releaseJobImage(workflow);
    if (!expected) return [];
    const content = committed[file];
    let committedImage: string | null = null;
    if (content) {
      try {
        committedImage = releaseJobImage(parse(content) ?? {});
      } catch {
        committedImage = null;
      }
    }
    return committedImage === expected
      ? []
      : [{ file, expected, committed: committedImage }];
  });

/**
 * the release job image in the committed workflows must be the one this
 * catladder version generates. The image tag encodes the image
 * definition, so an older tag means an older release script — which is
 * more than cosmetics: the semantic-release image before this check
 * pushed with the workflow token and ignored the release deploy key,
 * so every release on a repository with merge gating failed on GH013
 * while `project setup` and the deploy-key checks reported all green.
 *
 * Needs no `gh` login — only the config and the committed files.
 */
export const checkGithubReleaseWorkflow = async (
  report: DoctorReport,
  config: Config,
) => {
  if (!getEnabledPipelineTypes(config).includes("github")) return;
  report.section("github release workflow");

  let generated: Workflows;
  try {
    const images = new JobImagesPlan(
      "github",
      config.images,
      await resolveGithubRegistryImage(config),
    );
    generated = await new GithubBackend().createWorkflows(config, images);
  } catch (e) {
    report.warn(`could not generate the github workflows (${e.message})`);
    return;
  }

  const files = Object.keys(generated).filter((file) =>
    releaseJobImage(generated[file]),
  );
  const committed: Record<string, string | null> = {};
  for (const file of files) {
    committed[file] = await readFile(
      join(WORKFLOWS_FOLDER, file),
      "utf8",
    ).catch(() => null);
  }

  const drift = findReleaseJobImageDrift(generated, committed);
  if (drift.length === 0) {
    report.ok(
      `release job image up to date in ${files.length} generated workflow(s)`,
    );
    return;
  }
  for (const { file, expected, committed } of drift) {
    report.fail(
      committed
        ? `${WORKFLOWS_FOLDER}/${file}: the release job runs ${committed}, this catladder version generates ${expected} — the committed workflow was generated by an older catladder (its release script may push with the workflow token, ignoring the release deploy key)`
        : `${WORKFLOWS_FOLDER}/${file}: missing or without a '${RELEASE_JOB_NAME}' job (expected image ${expected})`,
      "run: catenv (and commit the regenerated workflows)",
    );
  }
};
