import { writeFile } from "fs/promises";
import { stringify } from "yaml";
import packageInfos from "../packageInfos";

export const getAutoGeneratedHeader = (commentChar: string) => {
  return [
    "-------------------------------------------------",
    `🐱 🔨 This file is generated by catladder v${packageInfos.version}`,
    `🚨 Do not edit this file manually 🚨`,
    "-------------------------------------------------",
  ]
    .map((line) => `${commentChar} ${line}`)
    .join("\n")
    .concat("\n");
};

export const writeGeneratedFile = async (
  path: string,
  content: string,
  {
    commentChar,
  }: {
    commentChar: string;
  },
) => {
  await writeFile(
    path,
    // need to spread out the jobs, forgot why
    [getAutoGeneratedHeader(commentChar), content].join("\n"),
    {
      encoding: "utf-8",
    },
  );
};

export const writeYamlfile = async (path: string, data: any) => {
  await writeGeneratedFile(path, stringify(data), {
    commentChar: "#",
  });
};
