#!/bin/bash
set -e

echo "Deploy to kubernetes"
echo "Release: $RELEASE_NAME"
echo "URL (canonical): $HOST_INTERNAL"

# this bash-brainfuck simply splits $helmArgs by newline to an array...
readarray -t helmArgsArray <<<"$HELM_ARGS"

#Log the time until selfdestruct in case of review environment
if [[ ${ENV_SHORT} == "review" ]]; then echo "NOTE - This deployment will stop itself after 2 weeks"; fi

if [[ ${ENV_SHORT} == "review" ]]; then
    # auto rollback
    set +e # disable fail job on error
    helmStatus=$(helm status --namespace $KUBE_NAMESPACE $RELEASE_NAME 2>/dev/null | awk -F': ' -v key="STATUS" '$1==key {print $2}')
    helmRevision=$(helm status --namespace $KUBE_NAMESPACE $RELEASE_NAME 2>/dev/null | awk -F': ' -v key="REVISION" '$1==key {print $2}')
    if [ "$helmStatus" = "failed" ] || [ "$helmStatus" = "pending-install" ] || [ "$helmStatus" = "pending-upgrade" ]; then
        # rollback
        echo "helm deployment is pending or failed, rollback (only on review)..."
        if [ "$helmRevision" = "1" ]; then
            helm uninstall "$RELEASE_NAME" --namespace "$KUBE_NAMESPACE"
        else
            helm rollback "$RELEASE_NAME" --namespace "$KUBE_NAMESPACE"
        fi

    fi
    set -e # reenable

fi

echo "doing helm upgrade"
helm upgrade --install "$RELEASE_NAME" "$HELM_GITLAB_CHART_NAME" \
    --timeout="30m0s" \
    --set global.appName="$KUBE_APP_NAME" \
    --set global.appPrefix="$KUBE_APP_NAME_PREFIX" \
    --set global.ENV_SHORT="$ENV_SHORT" \
    --set global.BUILD_ID="$BUILD_INFO_ID" \
    --set image.repository="$CI_REGISTRY_IMAGE" \
    --set image.pullSecret="$KUBE_DOCKER_IMAGE_PULL_SECRET" \
    --set image.name="$DOCKER_IMAGE_NAME" \
    --set image.tag="$DOCKER_IMAGE_TAG" \
    --set image.pullPolicy=IfNotPresent \
    --set application.hostCanonical="$HOST_INTERNAL" \
    --set mongodb.fullnameOverride=$KUBE_APP_NAME-mongodb \
    --set mailhog.fullnameOverride=$KUBE_APP_NAME-mailhog \
    --set gitlab.visualReviewEnabled="$GITLAB_VISUAL_REVIEW_ENABLED" \
    --set gitlab.app="$CI_PROJECT_PATH_SLUG" \
    --set gitlab.projectPath="$CI_PROJECT_PATH" \
    --set gitlab.mergeRequestId="$CI_MERGE_REQUEST_IID" \
    --set gitlab.projectId="$CI_PROJECT_ID" \
    --set gitlab.env="$CI_ENVIRONMENT_SLUG" \
    --set namespace="$KUBE_NAMESPACE" \
    --namespace="$KUBE_NAMESPACE" \
    ${helmArgsArray[@]} \
    --values __all_values.yml
