apiVersion: v2
description: a chart to rule them all
name: the-panter-chart
version: 1.0.0 # should not matter

dependencies:
  - name: mongodb
    version: 12.1.27
    condition: mongodb.enabled
    repository: https://charts.bitnami.com/bitnami
  - name: mailhog
    version: 5.0.1
    condition: mailhog.enabled
    repository: https://codecentric.github.io/helm-charts
