import { execFileSync } from "child_process";
import { describe, expect, it } from "vitest";
import type { Config } from "../../../types";
import { GithubBackend } from "../GithubBackend";

const cloudRun = {
  type: "google-cloudrun",
  projectId: "some-project",
  region: "europe-west6",
};

const baseConfig = {
  appName: "test-app",
  customerName: "pan",
  pipelines: { github: true },
  store: {
    gcloudProjects: { "some-project": { projectNumber: "123456789012" } },
  },
  components: {
    api: {
      dir: "api",
      build: { type: "node" },
      deploy: cloudRun,
      verify: { command: "yarn e2e" },
    },
    web: {
      dir: "web",
      build: { type: "node" },
      deploy: cloudRun,
    },
  },
} as unknown as Config;

const workflowsOf = (config: object) =>
  new GithubBackend().createWorkflows(config as unknown as Config);

const DELIVERY = [
  "api-docker-review",
  "api-deploy-review",
  "api-verify-review",
  "web-docker-review",
  "web-deploy-review",
];

describe("github review deploy workflow", () => {
  it("is not generated by default: review apps deploy in the review workflow", async () => {
    const workflows = await workflowsOf(baseConfig);
    expect(workflows["catladder-deploy-review.yml"]).toBeUndefined();
    expect(Object.keys(workflows["catladder-review.yml"].jobs)).toEqual(
      expect.arrayContaining(DELIVERY),
    );
  });

  it("deploys in the review run when the label is set at its start, else via the guarded deploy workflow (optIn)", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { deploy: "optIn" },
    });
    const review = workflows["catladder-review.yml"];
    const deploy = workflows["catladder-deploy-review.yml"];

    // CI stays: tests, lint, audit and the app build, plus the aggregate
    expect(Object.keys(review.jobs)).toEqual(
      expect.arrayContaining([
        "api-test-review",
        "api-lint-review",
        "api-app-review",
        "catladder-ok",
        "catladder-review-deploy-trigger",
      ]),
    );
    // the label is known at the start of the run: the chains deploy in
    // it (one run, one app build) behind that condition ...
    for (const id of DELIVERY) {
      expect(review.jobs[id].if).toContain(
        "contains(github.event.pull_request.labels.*.name, 'catladder:review-app')",
      );
    }
    // ... a skipped chain is no CI failure, a failed one is
    const okScript = review.jobs["catladder-ok"].steps[0].run ?? "";
    expect(okScript).toContain(` ${[...DELIVERY].sort().join(" ")} `);
    expect(okScript).not.toContain("api-test-review ");
    // ... with the stable review app result in the same run
    expect(review.jobs["catladder-review-app-ok"].if).toBe(
      "${{ always() && (contains(github.event.pull_request.labels.*.name, 'catladder:review-app')) }}",
    );
    // the trigger only hands over when the run itself didn't deploy
    expect(review.jobs["catladder-review-deploy-trigger"]).toMatchObject({
      needs: ["catladder-ok"],
      if: "${{ success() && !(contains(github.event.pull_request.labels.*.name, 'catladder:review-app')) }}",
    });

    // the chains plus the rebuilt app builds, never the quality jobs
    const deployJobs = Object.keys(deploy.jobs);
    expect(deployJobs).toEqual(
      expect.arrayContaining([
        "catladder-review-deploy-guard",
        "api-app-review",
        ...DELIVERY,
      ]),
    );
    expect(deployJobs.filter((id) => /-(test|lint|audit)-/.test(id))).toEqual(
      [],
    );
    expect(deploy.jobs["api-deploy-review"].needs).not.toContain(
      "api-test-review",
    );
    // the release image is no review chain's concern
    expect(deployJobs).not.toContain("catladder-image-semantic-release");

    for (const [id, job] of Object.entries(deploy.jobs)) {
      if (id === "catladder-review-deploy-guard") continue;
      expect(job.needs).toContain("catladder-review-deploy-guard");
      expect(job.if).toContain(
        "needs.catladder-review-deploy-guard.outputs.deploy == 'true'",
      );
    }

    expect(deploy.on).toMatchObject({
      workflow_dispatch: { inputs: { pr: { required: true } } },
      pull_request: { types: ["labeled"] },
    });
    expect(deploy.env?.CL_PR_NUMBER).toBe(
      "${{ github.event.number || inputs.pr }}",
    );
    // other labels must not cancel a deploy in flight
    expect(deploy.concurrency?.group).toContain(
      "github.event.label.name == 'catladder:review-app'",
    );
  });

  it("reports one stable aggregate for merge gates, as check and commit status", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { deploy: "optIn" },
    });
    const deploy = workflows["catladder-deploy-review.yml"];
    const aggregate = deploy.jobs["catladder-review-app-ok"];
    expect(aggregate.name).toBe("catladder review app ✅");
    // waits for everything, and only reports when the run deploys
    expect(aggregate.needs).toEqual(
      expect.arrayContaining(["catladder-review-deploy-guard", ...DELIVERY]),
    );
    expect(aggregate.if).toBe(
      "${{ always() && (needs.catladder-review-deploy-guard.outputs.deploy == 'true') }}",
    );
    expect(aggregate.permissions).toEqual({ statuses: "write" });
    expect(aggregate.steps[0].run).toContain('context="catladder review app"');
    // a cancelled (superseded/stopped) run reports nothing instead of red
    expect(aggregate.steps[0].run).toContain(
      "cancelled — no review app result reported",
    );
    // the guard marks the deploy in flight on the pull request
    const guardSteps = deploy.jobs["catladder-review-deploy-guard"].steps;
    expect(guardSteps.at(-1)?.run).toContain("state=pending");
  });

  it("stops the review apps when the opt-in label is removed", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { deploy: "optIn" },
    });
    const stop = workflows["catladder-review-stop.yml"];
    expect(stop.on).toMatchObject({
      pull_request: { types: ["closed", "unlabeled"] },
    });
    for (const job of Object.values(stop.jobs)) {
      expect(job.if).toContain(
        "(github.event.action == 'unlabeled' && github.event.label.name == 'catladder:review-app')",
      );
    }
    // shares the deploy group: a deploy in flight is cancelled first
    expect(stop.concurrency?.group).toMatch(/^catladder-review-deploy-/);
    // ... and waits for review runs deploying outside that group
    expect(stop.jobs["catladder-wait-review-runs"].steps[0].run).toContain(
      "gh run cancel",
    );
    expect(stop.jobs["api-stop-review"].needs).toContain(
      "catladder-wait-review-runs",
    );
  });

  it("opt-out switches on removing the skip label, off on adding it", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { deploy: "optOut", skipLabel: "no-preview" },
    });
    expect(workflows["catladder-deploy-review.yml"].on).toMatchObject({
      pull_request: { types: ["unlabeled"] },
    });
    expect(workflows["catladder-review-stop.yml"].on).toMatchObject({
      pull_request: { types: ["closed", "labeled"] },
    });
  });

  it.each([
    [
      { deploy: "optOut" },
      "!contains(github.event.pull_request.labels.*.name, 'catladder:no-review-app')",
    ],
    [
      { deploy: "optIn", drafts: "checksOnly" },
      "contains(github.event.pull_request.labels.*.name, 'catladder:review-app') && !github.event.pull_request.draft",
    ],
    [{ drafts: "checksOnly" }, "!github.event.pull_request.draft"],
  ])("in-run deploy condition for %j", async (reviewApps, condition) => {
    const workflows = await workflowsOf({ ...baseConfig, reviewApps });
    expect(workflows["catladder-review.yml"].jobs["api-deploy-review"].if).toBe(
      `\${{ ${condition} }}`,
    );
  });

  it("manual: dispatch only, no trigger job", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { deploy: "manual" },
    });
    expect(workflows["catladder-deploy-review.yml"].on).not.toHaveProperty(
      "pull_request",
    );
    // never deploys on its own: the chains only live in the dispatch
    for (const id of DELIVERY) {
      expect(workflows["catladder-review.yml"].jobs[id]).toBeUndefined();
    }
    expect(
      workflows["catladder-review.yml"].jobs["catladder-review-deploy-trigger"],
    ).toBeUndefined();
  });

  it("drafts: checksOnly deploys once a draft is marked ready", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { drafts: "checksOnly" },
    });
    expect(workflows["catladder-deploy-review.yml"].on).toMatchObject({
      pull_request: { types: ["ready_for_review"] },
    });
    expect(
      workflows["catladder-review.yml"].jobs["catladder-review-deploy-trigger"],
    ).toBeDefined();
  });

  it("drafts: skip skips every job of the review workflow for drafts", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { drafts: "skip" },
    });
    const review = workflows["catladder-review.yml"];
    expect(review.on).toMatchObject({
      pull_request: {
        types: ["opened", "synchronize", "reopened", "ready_for_review"],
      },
    });
    for (const job of Object.values(review.jobs)) {
      expect(job.if).toContain("!github.event.pull_request.draft");
    }
    expect(review.jobs["catladder-ok"].if).toBe(
      "${{ (always()) && (!github.event.pull_request.draft) }}",
    );
    // not gated: the review apps still deploy in the review workflow
    expect(workflows["catladder-deploy-review.yml"]).toBeUndefined();
  });

  it("a component with a manual review deploy moves alone, keeping the PR's CI intact", async () => {
    const components = baseConfig.components as Record<string, object>;
    const workflows = await workflowsOf({
      ...baseConfig,
      components: {
        ...components,
        web: {
          ...components.web,
          env: { review: { deploy: { when: "manual" } } },
        },
      },
    });
    const review = workflows["catladder-review.yml"];
    const deploy = workflows["catladder-deploy-review.yml"];
    // api still deploys automatically, web's tests still run
    expect(Object.keys(review.jobs)).toEqual(
      expect.arrayContaining([
        "api-deploy-review",
        "web-test-review",
        "catladder-ok",
      ]),
    );
    expect(Object.keys(review.jobs)).not.toContain("web-deploy-review");
    expect(Object.keys(deploy.jobs)).toEqual(
      expect.arrayContaining(["web-docker-review", "web-deploy-review"]),
    );
    expect(Object.keys(deploy.jobs)).not.toContain("api-deploy-review");
    // no label policy: no automatic trigger
    expect(review.jobs["catladder-review-deploy-trigger"]).toBeUndefined();
    // the generic manual-task dispatch no longer offers the review deploy
    expect(
      JSON.stringify(workflows["catladder-deploy.yml"]?.on ?? {}),
    ).not.toContain("web-deploy-review");
  });

  // the aggregate's verdict runs jq on the needs context — exercise the
  // real script (snapshots alone never ran it: a jq scoping bug made
  // catladder ✅ crash instead of judging)
  const hasJq = (() => {
    try {
      execFileSync("jq", ["--version"]);
      return true;
    } catch {
      return false;
    }
  })();
  it.skipIf(!hasJq)(
    "catladder ✅ accepts skipped review chains, fails on real failures",
    async () => {
      const workflows = await workflowsOf({
        ...baseConfig,
        reviewApps: { deploy: "optIn" },
      });
      const script =
        workflows["catladder-review.yml"].jobs["catladder-ok"].steps[0].run ??
        "";
      const verdict = (needs: Record<string, string>) => {
        const json = JSON.stringify(
          Object.fromEntries(
            Object.entries(needs).map(([id, result]) => [
              id,
              { result, outputs: {} },
            ]),
          ),
        );
        try {
          execFileSync(
            "bash",
            ["-c", script.replace("${{ toJSON(needs) }}", json)],
            { stdio: "pipe" },
          );
          return "ok";
        } catch {
          return "failed";
        }
      };
      expect(
        verdict({
          "api-test-review": "success",
          "api-deploy-review": "skipped",
        }),
      ).toBe("ok");
      expect(
        verdict({
          "api-test-review": "skipped",
          "api-deploy-review": "skipped",
        }),
      ).toBe("failed");
      expect(
        verdict({
          "api-test-review": "success",
          "api-deploy-review": "failure",
        }),
      ).toBe("failed");
      expect(
        verdict({
          "api-test-review": "cancelled",
          "api-deploy-review": "success",
        }),
      ).toBe("failed");
    },
  );
});
