import { describe, expect, it } from "vitest";
import type { Config } from "../../../types";
import { GithubBackend } from "../GithubBackend";

const cloudRun = {
  type: "google-cloudrun",
  projectId: "some-project",
  region: "europe-west6",
};

const baseConfig = {
  appName: "test-app",
  customerName: "pan",
  pipelines: { github: true },
  store: {
    gcloudProjects: { "some-project": { projectNumber: "123456789012" } },
  },
  components: {
    api: {
      dir: "api",
      build: { type: "node" },
      deploy: cloudRun,
      verify: { command: "yarn e2e" },
    },
    web: {
      dir: "web",
      build: { type: "node" },
      deploy: cloudRun,
    },
  },
} as unknown as Config;

const workflowsOf = (config: object) =>
  new GithubBackend().createWorkflows(config as unknown as Config);

const DELIVERY = [
  "api-docker-review",
  "api-deploy-review",
  "api-verify-review",
  "web-docker-review",
  "web-deploy-review",
];

describe("github review deploy workflow", () => {
  it("is not generated by default: review apps deploy in the review workflow", async () => {
    const workflows = await workflowsOf(baseConfig);
    expect(workflows["catladder-deploy-review.yml"]).toBeUndefined();
    expect(Object.keys(workflows["catladder-review.yml"].jobs)).toEqual(
      expect.arrayContaining(DELIVERY),
    );
  });

  it("moves the delivery chains of all components behind the guard (optIn)", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { deploy: "optIn" },
    });
    const review = workflows["catladder-review.yml"];
    const deploy = workflows["catladder-deploy-review.yml"];

    // CI stays: tests, lint, audit and the app build, plus the aggregate
    expect(Object.keys(review.jobs)).toEqual(
      expect.arrayContaining([
        "api-test-review",
        "api-lint-review",
        "api-app-review",
        "catladder-ok",
        "catladder-review-deploy-trigger",
      ]),
    );
    for (const id of DELIVERY) {
      expect(Object.keys(review.jobs)).not.toContain(id);
    }
    expect(review.jobs["catladder-review-deploy-trigger"].needs).toEqual([
      "catladder-ok",
    ]);

    // the chains plus the rebuilt app builds, never the quality jobs
    const deployJobs = Object.keys(deploy.jobs);
    expect(deployJobs).toEqual(
      expect.arrayContaining([
        "catladder-review-deploy-guard",
        "api-app-review",
        ...DELIVERY,
      ]),
    );
    expect(deployJobs.filter((id) => /-(test|lint|audit)-/.test(id))).toEqual(
      [],
    );
    expect(deploy.jobs["api-deploy-review"].needs).not.toContain(
      "api-test-review",
    );
    // the release image is no review chain's concern
    expect(deployJobs).not.toContain("catladder-image-semantic-release");

    for (const [id, job] of Object.entries(deploy.jobs)) {
      if (id === "catladder-review-deploy-guard") continue;
      expect(job.needs).toContain("catladder-review-deploy-guard");
      expect(job.if).toContain(
        "needs.catladder-review-deploy-guard.outputs.deploy == 'true'",
      );
    }

    expect(deploy.on).toMatchObject({
      workflow_dispatch: { inputs: { pr: { required: true } } },
      pull_request: { types: ["labeled"] },
    });
    expect(deploy.env?.CL_PR_NUMBER).toBe(
      "${{ github.event.number || inputs.pr }}",
    );
    // other labels must not cancel a deploy in flight
    expect(deploy.concurrency?.group).toContain(
      "github.event.label.name == 'catladder:review-app'",
    );
  });

  it("stops the review apps when the opt-in label is removed", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { deploy: "optIn" },
    });
    const stop = workflows["catladder-review-stop.yml"];
    expect(stop.on).toMatchObject({
      pull_request: { types: ["closed", "unlabeled"] },
    });
    for (const job of Object.values(stop.jobs)) {
      expect(job.if).toContain(
        "(github.event.action == 'unlabeled' && github.event.label.name == 'catladder:review-app')",
      );
    }
    // shares the deploy group: a deploy in flight is cancelled first
    expect(stop.concurrency?.group).toMatch(/^catladder-review-deploy-/);
  });

  it("opt-out switches on removing the skip label, off on adding it", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { deploy: "optOut", skipLabel: "no-preview" },
    });
    expect(workflows["catladder-deploy-review.yml"].on).toMatchObject({
      pull_request: { types: ["unlabeled"] },
    });
    expect(workflows["catladder-review-stop.yml"].on).toMatchObject({
      pull_request: { types: ["closed", "labeled"] },
    });
  });

  it("manual: dispatch only, no trigger job", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { deploy: "manual" },
    });
    expect(workflows["catladder-deploy-review.yml"].on).not.toHaveProperty(
      "pull_request",
    );
    expect(
      workflows["catladder-review.yml"].jobs["catladder-review-deploy-trigger"],
    ).toBeUndefined();
  });

  it("drafts: ci deploys once a draft is marked ready", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { drafts: "ci" },
    });
    expect(workflows["catladder-deploy-review.yml"].on).toMatchObject({
      pull_request: { types: ["ready_for_review"] },
    });
    expect(
      workflows["catladder-review.yml"].jobs["catladder-review-deploy-trigger"],
    ).toBeDefined();
  });

  it("drafts: none skips every job of the review workflow for drafts", async () => {
    const workflows = await workflowsOf({
      ...baseConfig,
      reviewApps: { drafts: "none" },
    });
    const review = workflows["catladder-review.yml"];
    expect(review.on).toMatchObject({
      pull_request: {
        types: ["opened", "synchronize", "reopened", "ready_for_review"],
      },
    });
    for (const job of Object.values(review.jobs)) {
      expect(job.if).toContain("!github.event.pull_request.draft");
    }
    expect(review.jobs["catladder-ok"].if).toBe(
      "${{ (always()) && (!github.event.pull_request.draft) }}",
    );
    // not gated: the review apps still deploy in the review workflow
    expect(workflows["catladder-deploy-review.yml"]).toBeUndefined();
  });

  it("a component with a manual review deploy moves alone, keeping the PR's CI intact", async () => {
    const components = baseConfig.components as Record<string, object>;
    const workflows = await workflowsOf({
      ...baseConfig,
      components: {
        ...components,
        web: {
          ...components.web,
          env: { review: { deploy: { when: "manual" } } },
        },
      },
    });
    const review = workflows["catladder-review.yml"];
    const deploy = workflows["catladder-deploy-review.yml"];
    // api still deploys automatically, web's tests still run
    expect(Object.keys(review.jobs)).toEqual(
      expect.arrayContaining([
        "api-deploy-review",
        "web-test-review",
        "catladder-ok",
      ]),
    );
    expect(Object.keys(review.jobs)).not.toContain("web-deploy-review");
    expect(Object.keys(deploy.jobs)).toEqual(
      expect.arrayContaining(["web-docker-review", "web-deploy-review"]),
    );
    expect(Object.keys(deploy.jobs)).not.toContain("api-deploy-review");
    // no label policy: no automatic trigger
    expect(review.jobs["catladder-review-deploy-trigger"]).toBeUndefined();
    // the generic manual-task dispatch no longer offers the review deploy
    expect(
      JSON.stringify(workflows["catladder-deploy.yml"]?.on ?? {}),
    ).not.toContain("web-deploy-review");
  });
});
