import { describe, expect, it } from "vitest";
import { findReleaseJobImageDrift } from "../doctor/checkGithubReleaseWorkflow";

const CURRENT = "ghcr.io/fiulag/nautilus/catladder-semantic-release:abc123";
const OLD = "ghcr.io/fiulag/nautilus/catladder-semantic-release:0ld";

const workflow = (image: string) => ({
  name: "🚀 catladder create release",
  on: { workflow_dispatch: {} },
  jobs: {
    "create-release": {
      name: "create release",
      "runs-on": "ubuntu-latest",
      container: { image },
      steps: [{ run: "semanticRelease" }],
    },
  },
});

const committedYaml = (image: string) => `
name: 🚀 catladder create release
jobs:
  create-release:
    name: create release
    container:
      image: ${image}
`;

const generated = {
  "catladder-create-release.yml": workflow(CURRENT),
  "catladder-review.yml": {
    name: "🛠️ catladder review",
    on: {},
    jobs: { lint: { name: "lint", "runs-on": "ubuntu-latest", steps: [] } },
  },
} as any;

describe("findReleaseJobImageDrift", () => {
  it("is quiet when the committed release job runs the generated image", () => {
    expect(
      findReleaseJobImageDrift(generated, {
        "catladder-create-release.yml": committedYaml(CURRENT),
      }),
    ).toEqual([]);
  });

  it("reports a committed workflow generated by an older catladder (older image tag)", () => {
    expect(
      findReleaseJobImageDrift(generated, {
        "catladder-create-release.yml": committedYaml(OLD),
      }),
    ).toEqual([
      {
        file: "catladder-create-release.yml",
        expected: CURRENT,
        committed: OLD,
      },
    ]);
  });

  it("reports a missing or unparsable committed workflow", () => {
    expect(
      findReleaseJobImageDrift(generated, {
        "catladder-create-release.yml": null,
      }),
    ).toEqual([
      {
        file: "catladder-create-release.yml",
        expected: CURRENT,
        committed: null,
      },
    ]);
    expect(
      findReleaseJobImageDrift(generated, {
        "catladder-create-release.yml": "jobs: [not: a: workflow",
      }),
    ).toEqual([
      {
        file: "catladder-create-release.yml",
        expected: CURRENT,
        committed: null,
      },
    ]);
  });

  it("only looks at workflows carrying a release job", () => {
    expect(findReleaseJobImageDrift(generated, {})).toHaveLength(1);
  });
});
