#!/bin/bash

# 1. create "@semantic-release/changelog"
# 2. commit it to git (and push)
# 3. optional: update package.json

# better branches settings: https://github.com/semantic-release/semantic-release/issues/1581

echo "doing semantic release"

yarn global add --silent semantic-release \
  @semantic-release/commit-analyzer \
  @semantic-release/release-notes-generator \
  https://github.com/panter/git.git#b4037626cc583d3e9f7995ea0604b23730d0a22e \
  @semantic-release/changelog \
  @semantic-release/gitlab \
  @semantic-release/exec

if [ ! -e .releaserc ]; then
  cat >.releaserc <<EOF
{
  "plugins": [
      [
      "@semantic-release/commit-analyzer",
      {
        preset: "angular",
        releaseRules: [
          { breaking: true, release: "major" },
          { revert: true, release: "patch" },

          { type: "feat", release: "minor" },
          { type: "docs", release: "patch" },
          { type: "fix", release: "patch" },
          { type: "perf", release: "patch" },
          # always fall back to a patch release
          {
            message: "*",
            release: "patch",
          },
        ],
      },
    ],
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    ["@semantic-release/git", {
      "message": "chore(\${branch.type}): \${nextRelease.version}\n\n\${nextRelease.notes}"
    }],
    ["@semantic-release/gitlab", {
      "gitlabUrl": "https://git.panter.ch"
    }]
    ],
  "branches": [
    "+([0-9])?(.{+([0-9]),x}).x",
    "master",
    "main",
    "next",
    "next-major",
    {
      "name": "beta",
      "prerelease": true
    },
    {
      "name": "alpha",
      "prerelease": true
    }
  ],
}
EOF
fi
