import { existsSync } from "fs";
import { mkdir, readdir, readFile, rm } from "fs/promises";
import { dirname, join } from "path";
import type { CatenvContext } from "../catenv";
import { AGENT_SKILL_PREFIX, getShippedSkills } from "./shippedSkills";
import { AGENT_SKILL_TARGET_DIRS, getAgentSkillTargets } from "./types";

/**
 * marks a materialized skill file as generated. Cleanup only ever
 * removes skill directories whose SKILL.md carries this marker, so a
 * user's own skills are never touched — even if they picked a
 * `catladder-*` name.
 */
export const AGENT_SKILL_GENERATED_MARKER =
  "<!-- 🐱 🔨 generated by catladder — do not edit manually, this file is overwritten on every catenv run -->";

/**
 * inserts the generated-marker into a markdown file: after the YAML
 * frontmatter when there is one (a leading comment would break
 * frontmatter parsing), at the top otherwise
 */
export const injectGeneratedMarker = (content: string): string => {
  if (content.startsWith("---\n")) {
    const frontmatterEnd = content.indexOf("\n---\n", 3);
    if (frontmatterEnd !== -1) {
      const bodyStart = frontmatterEnd + "\n---\n".length;
      return (
        content.slice(0, bodyStart) +
        "\n" +
        AGENT_SKILL_GENERATED_MARKER +
        "\n" +
        content.slice(bodyStart)
      );
    }
  }
  return AGENT_SKILL_GENERATED_MARKER + "\n\n" + content;
};

/**
 * removes previously materialized catladder skills from ALL known
 * target directories (not just the enabled ones), so that opting out
 * or narrowing the targets doesn't leave stale copies behind
 */
const cleanupGeneratedAgentSkills = async (rootDir: string) => {
  for (const targetDir of Object.values(AGENT_SKILL_TARGET_DIRS)) {
    const skillsRoot = join(rootDir, targetDir);
    if (!existsSync(skillsRoot)) continue;
    for (const entry of await readdir(skillsRoot)) {
      if (!entry.startsWith(AGENT_SKILL_PREFIX)) continue;
      const skillMd = join(skillsRoot, entry, "SKILL.md");
      if (!existsSync(skillMd)) continue;
      const content = await readFile(skillMd, "utf-8");
      if (!content.includes(AGENT_SKILL_GENERATED_MARKER)) continue;
      await rm(join(skillsRoot, entry), { recursive: true, force: true });
    }
  }
};

/**
 * materializes the agent skills shipped with catladder (usage guides
 * for AI coding agents) into the repository's agent skill directories,
 * so agents working in the project use knowledge matching the installed
 * catladder version. Opt out or narrow the targets via
 * `agentSkills` in the config.
 */
export const generateAgentSkills = async (
  context: CatenvContext,
  rootDir = ".",
) => {
  await cleanupGeneratedAgentSkills(rootDir);

  const targets = getAgentSkillTargets(context.config.agentSkills);
  if (targets.length === 0) return;

  const skills = getShippedSkills();
  for (const target of targets) {
    for (const skill of skills) {
      for (const file of skill.files) {
        const path = join(
          rootDir,
          AGENT_SKILL_TARGET_DIRS[target],
          skill.name,
          file.relativePath,
        );
        await mkdir(dirname(path), { recursive: true });
        const content = file.relativePath.endsWith(".md")
          ? injectGeneratedMarker(file.content)
          : file.content;
        await context.fileWriter.writeGeneratedFileRaw(path, content);
      }
    }
  }
};
